from _typeshed import Incomplete
from django.test import TestCase
from warehouse.models import Brand as Brand

class BrandModel(TestCase):
    Brand: Incomplete
    def setUp(self) -> None: ...
    def test_str_method(self) -> None: ...
    def test_verbose_name(self) -> None: ...
    def test_save_method(self) -> None: ...
