from django.test import TestCase
from warehouse.models import Brand as Brand, Category as Category, Product as Product

class ProductModel(TestCase):
    @classmethod
    def setUpClass(cls) -> None: ...
    def test_str_method(self) -> None: ...
    def test_repr_method(self) -> None: ...
    def test_verbose_name(self) -> None: ...
    def test_save_method(self) -> None: ...
