from django.test import TestCase
from warehouse.models import Product as Product
from warehouse.repository.generator_layer import WarehouseDataGenerator as WarehouseDataGenerator

class TestDataGenerator(TestCase):
    @classmethod
    def setUpClass(cls) -> None: ...
    def test_create_products(self) -> None: ...
    def test_total_tags(self) -> None: ...
    def test_product_without_tags(self) -> None: ...
    def test_product_voucher(self) -> None: ...
    def test_product_active(self) -> None: ...
    def test_product_brand_and_category(self) -> None: ...
